export default {
  products: [
    {
      id: 1,
      title: 'Ball FC Dynamo',
      description:
        'With this ball, decorated with the logo of FC Dynamo Moscow, every fan has the opportunity to score his golden goal and feel like a part of his favorite team. In professional football leagues and tournaments held under the auspices of FIFA, a size five ball with a circumference of 68–70 cm and a weight of 410–450 grams is mandatory.',
      price: 2790,
      discountPercentage: 15,
      stock: 25,
      brand: 'FC Dynamo',
      category: 'balls',
      thumbnail: '../assets/img/products-1-1.jpg',
      images: [],
    },
    {
      id: 2,
      title: 'Diary FC Dynamo',
      description:
        'The corporate blue A5 diary with the logo and the slogan "One life - one team" is a great gift for FC Dynamo Moscow fans who support the team even at the office or at school. The diary is lined, with a cover made of tactilely pleasant material with a soft-touch coating.',
      price: 1190,
      discountPercentage: 20,
      stock: 9,
      brand: 'FC Dynamo',
      category: 'souvenirs',
      thumbnail: '',
      images: [],
    },
    {
      id: 3,
      title: 'T-shirt FC Dynamo',
      description:
        'Classic Dynamo T-shirt with a round collar. Colour: White with blue embroidered club emblem and contrasting blue and white piping on the collar and sleeves. Emblem: 3D embroidery. Material: 95% cotton, 5% lycra. Production: Russia. Official products of FC Dynamo Moscow.',
      price: 1590,
      discountPercentage: 15,
      stock: 18,
      brand: 'FC Dynamo',
      category: 'uniforms',
      thumbnail: '',
      images: [],
    },
    {
      id: 4,
      title: 'Hat FC Dynamo',
      description:
        'Classic FC Dynamo Moscow hat with lapel. Size: standard adult size (head circumference 55 - 58 cm). Composition: 100% acrylic. Elements: three-dimensional embroidery of the team logo. Country of manufacture: China. This hat is a certified product, packed in individual packaging, protected by a hologram, has a unique barcode.',
      price: 990,
      discountPercentage: 20,
      stock: 27,
      brand: 'FC Dynamo',
      category: 'hats',
      thumbnail: '',
      images: [],
    },
    {
      id: 5,
      title: 'Scarf FC Dynamo',
      description:
        'One of the main attributes of a real fan is a scarf with the symbols of your favorite club. On the road, it is so important to support your favorite team, especially if the meeting is to be with a foreign club. To make it clear to everyone which team is the best, be sure to take to the stadium a scarf with knitted lettering FCDM - Football Club Dynamo Moscow - and a logo, some of the elements of which are embroidered with gold threads. Length 160 cm, width 16 cm Material: 90% acrylic, 10% lurex. Production: Russia.',
      price: 1990,
      discountPercentage: 15,
      stock: 45,
      brand: 'FC Dynamo',
      category: 'scarves',
      thumbnail: '',
      images: [],
    },
    {
      id: 7,
      title: 'Ball FC Manchester United',
      description:
        'Adidas Manchester United amateur soccer ball. Colour: Black with gray accents and orange club crest and Adidas logo. Material: TPU. Machine stitching. Size 5. Official products of the Manchester United club.',
      price: 2490,
      discountPercentage: 15,
      stock: 21,
      brand: 'FC Manchester United',
      category: 'balls',
      thumbnail: '',
      images: [],
    },
    {
      id: 8,
      title: 'Keychain FC Manchester United',
      description:
        'Metal keychain with the emblem of the football club Manchester United. Gold-colored metal, enamel coating - yellow-red. The size of the keychain is 4.5 cm. The keychain is one-sided, the color emblem is only on one side of the keychain. Official licensed product of Manchester United FC.',
      price: 830,
      discountPercentage: 20,
      stock: 17,
      brand: 'FC Manchester United',
      category: 'souvenirs',
      thumbnail: '',
      images: [],
    },
    {
      id: 9,
      title: 'Uniform FC Manchester United',
      description:
        'Buying a Manchester United jersey is a great idea to create a stylish sporty look. She will give confidence in the movements. You can also decorate a T-shirt with an alternative design by choosing to apply any number, name. The model is based on a new generation of water-repellent material. Practical and lightweight, it provides comfort and convenience. The innovative material does not absorb moisture, but brings it to the surface, where it gradually evaporates.',
      price: 3250,
      discountPercentage: 15,
      stock: 8,
      brand: 'FC Manchester United',
      category: 'uniforms',
      thumbnail: '',
      images: [],
    },
    {
      id: 10,
      title: 'Scarf FC Manchester United',
      description:
        'Red reversible jacquard knitted scarf with white stripes and black fringe. With the text "Manchester United" with 1878 details and club crests on each end. Official licensed product. Size 132 cm x 19 cm.',
      price: 2630,
      discountPercentage: 15,
      stock: 11,
      brand: 'FC Manchester United',
      category: 'scarves',
      thumbnail: '',
      images: [],
    },
    {
      id: 11,
      title: 'Ball FC Real Madrid',
      description:
        'Souvenir soccer ball with Real Madrid logo. Size 5. 26 panels. Colour: White with colored club emblem. Official licensed product.',
      price: 2390,
      discountPercentage: 15,
      stock: 17,
      brand: 'FC Real Madrid',
      category: 'balls',
      thumbnail: '',
      images: [],
    },
    {
      id: 12,
      title: 'Table rug FC Real Madrid',
      description:
        'Rug for the working (writing) table with the symbols of Real Madrid. The thickness of the mat is 1.9 mm. Dimensions: 34.5 x 49.5 cm. Official licensed product.',
      price: 350,
      discountPercentage: 20,
      stock: 5,
      brand: 'FC Real Madrid',
      category: 'souvenirs',
      thumbnail: '',
      images: [],
    },
    {
      id: 13,
      title: 'Uniform FC Real Madrid',
      description:
        'Lightweight water-repellent material of which the T-shirt is made is a guarantee of maximum comfort. Synthetics of the new generation brings moisture to the surface, passing it through its structure, and causes it to evaporate instantly.',
      price: 3250,
      discountPercentage: 15,
      stock: 11,
      brand: 'FC Real Madrid',
      category: 'uniforms',
      thumbnail: '',
      images: [],
    },
    {
      id: 14,
      title: 'Baseball cap FC Real Madrid',
      description:
        'Adidas Classic Real Madrid Baseball Cap Colour: purple with embroidered club crest, white Adidas branded stripes on the peak and Adidas label on the back. Emblem: embroidery on the edge; stripes and Adidas label; bulk embroidery. One size fits all for adults. Adjustable strap with metal clip (club logo embossed on the clip). Top material 100% cotton; inner tape 100% polyester. Official licensed product of the Real Madrid club.',
      price: 2150,
      discountPercentage: 15,
      stock: 3,
      brand: 'FC Real Madrid',
      category: 'hats',
      thumbnail: '',
      images: [],
    },
    {
      id: 15,
      title: 'Scarf FC Real Madrid',
      description:
        'Real Madrid jacquard knitted scarf. Material 100% acrylic. Size 136 x 17 cm. Official licensed product.',
      price: 1620,
      discountPercentage: 20,
      stock: 8,
      brand: 'FC Real Madrid',
      category: 'scarfs',
      thumbnail: '',
      images: [],
    },
    {
      id: 16,
      title: 'Ball PFC CSKA',
      description: 'Souvenir ball with PFC CSKA players, season 2022/2023. Ball size: 5',
      price: 4390,
      discountPercentage: 15,
      stock: 3,
      brand: 'PFC CSKA',
      category: 'balls',
      thumbnail: '',
      images: [],
    },
    {
      id: 17,
      title: 'Pennant PFC CSKA',
      description:
        'Triangular pennant with the emblem of PFC CSKA. Model: bilateral. Material: satin. Size: 15 x 22 cm. Country: Russia. Material composition: 100% polyester.',
      price: 490,
      discountPercentage: 20,
      stock: 7,
      brand: 'PFC CSKA',
      category: 'souvenirs',
      thumbnail: '',
      images: [],
    },
    {
      id: 18,
      title: 'Uniform PFC CSKA',
      description:
        'Game T-shirt PFC CSKA. The color is classic for the army: red-blue. Material: 100% breathable polyester. Official licensed product.',
      price: 5890,
      discountPercentage: 15,
      stock: 5,
      brand: 'PFC CSKA',
      category: 'uniforms',
      thumbnail: '',
      images: [],
    },
    {
      id: 19,
      title: 'Hat PFC CSKA',
      description:
        'Fleece-lined PFC CSKA hat. Size adult: head circumference 55 - 58 cm. Gender: Unisex (suitable for both men and women). Material composition: Acrylic 100%. Lining: Polyester 100%. Clothing style: casual.',
      price: 1290,
      discountPercentage: 15,
      stock: 11,
      brand: 'PFC CSKA',
      category: 'hats',
      thumbnail: '',
      images: [],
    },
    {
      id: 20,
      title: 'Scarf PFC CSKA',
      description:
        'Double-sided knitted scarf CSKA. Made in the classic club red and blue striped colors with the emblem and mascot at different ends. Material: acrylic. Made in Russia. Official licensed product of PFC CSKA.',
      price: 890,
      discountPercentage: 20,
      stock: 25,
      brand: 'PFC CSKA',
      category: 'scarves',
      thumbnail: '',
      images: [],
    },
  ],
};
